### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by kittykat**
Explicitly say that we're pre-release

### CODE REVIEW

**Comment by bmarty** [comment]
Is it conflicting with #181 ?

**Comment by ganfra** [comment]
@kittykat yeah it looks like its already done by manu

**Comment by bmarty** [comment]
No a problem to have 2 warnings about that.

**Review by bmarty — APPROVED** [review]

**Comment by kittykat** [comment]
I am fine with having this in or what Manu put in or both :+1:

**Pull request merged**
