### PR TITLE
Update readme.md and some other markdown files.

### LINKED ISSUE #944: Update Readme
- [ ] Update Screenshots
- [x] Contributing section: link to "help wanted" issue.
- [x] Link to element x android room instead of element android.
- [x] "ElementX" -> "Element X"
- [x] Hide info about rageshake
- [x] Weblate badge -> Localazy

### PR DESCRIPTION
**Pull request by bmarty**
Closes #944 

[Rendered README.md](https://github.com/vector-im/element-x-android/blob/7180e7f276a6a8f07d6a78d3080ae3d4a55b5f8d/README.md)

### CODE REVIEW

**Review by Hywan — APPROVED** [review]
Looks good!

**Comment by manuroe** [comment]
Should we add a link to #911 to share the state? 
It can replace "This app is currently in a pre-alpha release stage with only basic functionalities.". The app has not all feature of EA but what we have work.

I wonder if we should have a link to https://element.io/blog/element-x-experience-the-future-of-element/ to illustrate the story behind EX.

**Comment by bmarty** [comment]
> Should we add a link to #911 to share the state? It can replace "This app is currently in a pre-alpha release stage with only basic functionalities.". The app has not all feature of EA but what we have work.

I added the link in the "Status" section: https://github.com/vector-im/element-x-android/pull/970/files#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5R59

> I wonder if we should have a link to https://element.io/blog/element-x-experience-the-future-of-element/ to illustrate the story behind EX.

Yes, could point, will do.

**Comment by bmarty** [comment]
I have added 4fcc45a63c48a51daf06e4406454cc2541aa6502 . I am merging the PR, of course we can still iterate on those files regularly.

**Pull request merged**
