### PR TITLE
Fix test flakiness by warming up molecule tests

### PR DESCRIPTION
**Pull request by jonnyandrew**
## Type of change

- [ ] Feature
- [ ] Bugfix
- [x] Technical
- [ ] Other :

## Content

Reduce test flakiness by warming up molecule tests. Add a test rule that pre-runs a no-op molecule test and apply it to any presenter tests that use molecule.

## Motivation and context

Through profiling, I found that the first test of every test class takes a significant time to run. It turns out that molecule takes a significant amount of time to initialise when running in the first test of any given test class. This can create flakiness as tests will randomly exceed the default timeout of `runTest` (10 seconds).

To remove this source of flakiness, this solution ensures that the first call to initialise `moleculeFlow` occurs in a way that isn't impacted by the short default timeout.

image

Related issues:
- https://github.com/Kotlin/kotlinx.coroutines/issues/3800
- https://github.com/vector-im/element-x-android/pull/479 (similar solution)

## Screenshots / GIFs

N/A

## Tests

N/A

## Tested devices

- [ ] Physical
- [x] Emulator
- OS version(s):

## Checklist

- [ ] Changes have been tested on an Android device or Android emulator with API 23
- [ ] UI change has been tested on both light and dark themes
- [ ] Accessibility has been taken into account. See https://github.com/vector-im/element-x-android/blob/develop/CONTRIBUTING.md#accessibility
- [ ] Pull request is based on the develop branch
- [ ] Pull request includes a new file under ./changelog.d. See https://github.com/vector-im/element-x-android/blob/develop/CONTRIBUTING.md#changelog
- [ ] Pull request includes screenshots or videos if containing UI changes
- [ ] Pull request includes a [sign off](https://matrix-org.github.io/synapse/latest/development/contributing_guide.html#sign-off)
- [ ] You've made a self review of your PR

### CODE REVIEW

**Review by jmartinesp — APPROVED** [review]
LGTM, it's great that it doesn't affect CI times either!

**Review by bmarty — APPROVED** [review]
Thanks for looking at this.
In the spirit of point 3 of https://github.com/vector-im/element-x-android/blob/develop/docs/continuous_integration.md#rules :)

**Comment by julioromano** [comment]
Isn't this actually running the warm up before every test of the test class?
It seems from the wording of the PR that it'd be enough to run the warmup once for all the tests of a given test class, did I get it right?
If this is the case then would it be worth using `@ClassRule` instead of `@Rule`  ?

**Comment by julioromano** [comment]
> Yes it _should_ work as a class rule although I haven't tested this. Once warmed up the rule adds negligible overhead but perhaps we could still incrementally update these?

Followed up with: https://github.com/vector-im/element-x-android/pull/1310

**Pull request merged**
