### PR TITLE
Use @DayNightPreviews to correctly render the `PinIcon` in dark mode

### PR DESCRIPTION
**Pull request by julioromano**
- Fixes rendering of `-night` resources in screenshot tests by overriding the `nightMode` with `paparazzi.unsafeUpdateConfig()`.

### CODE REVIEW

**Comment by jmartinesp** [comment]
I think the screenshots aren't generated properly, both D and N variants use the dark version.

**Comment by julioromano** [comment]
> I think the screenshots aren't generated properly, both D and N variants use the dark version.

I've fixed a typo and generated the screenshots locally and I see the dark ones. Now I rerun the screenshot action, let's see.

**Comment by jmartinesp** [comment]
They still look the same, only the background changes: [Light](https://github.com/vector-im/element-x-android/blob/10f6dcc74cd9188c6a02af5c2bf358b465c2a92c/tests/uitests/src/test/snapshots/images/io.element.android.tests.uitests_ScreenshotTest_preview_tests%5Bio.element.android.libraries.designsystem.components_null_DefaultGroup_PinIconLightPreview-D_0_null%2CNEXUS_5%2C1.0%2Cen%5D.png) vs [Dark](https://github.com/vector-im/element-x-android/blob/10f6dcc74cd9188c6a02af5c2bf358b465c2a92c/tests/uitests/src/test/snapshots/images/io.element.android.tests.uitests_ScreenshotTest_preview_tests%5Bio.element.android.libraries.designsystem.components_null_DefaultGroup_PinIconLightPreview-N_1_null%2CNEXUS_5%2C1.0%2Cen%5D.png).

**Comment by julioromano** [comment]
> They still look the same, only the background changes: [Light](https://github.com/vector-im/element-x-android/blob/10f6dcc74cd9188c6a02af5c2bf358b465c2a92c/tests/uitests/src/test/snapshots/images/io.element.android.tests.uitests_ScreenshotTest_preview_tests%5Bio.element.android.libraries.designsystem.components_null_DefaultGroup_PinIconLightPreview-D_0_null%2CNEXUS_5%2C1.0%2Cen%5D.png) vs [Dark](https://github.com/vector-im/element-x-android/blob/10f6dcc74cd9188c6a02af5c2bf358b465c2a92c/tests/uitests/src/test/snapshots/images/io.element.android.tests.uitests_ScreenshotTest_preview_tests%5Bio.element.android.libraries.designsystem.components_null_DefaultGroup_PinIconLightPreview-N_1_null%2CNEXUS_5%2C1.0%2Cen%5D.png).

Do you spot any other differences now? I see none. Actually the only ones I had hoped to see (those with the pin icon in it) are also the same as before.

**Comment by julioromano** [comment]
> > Do you spot any other differences now? I see none. Actually the only ones I had hoped to see (those with the pin icon in it) are also the same as before.
> 
> No, they seem to be the same again. The drawable used is the one for the light theme on both, if I"m not mistaken.

Previews in Android studio look good though.
So this means that `@DayNightPreviews` works but that paparazzi doesn't use the `-night` resources somehow, correct?

**Comment by jmartinesp** [comment]
> Previews in Android studio look good though. So this means that `@DayNightPreviews` works but that paparazzi doesn't use the `-night` resources somehow, correct?

I just checked and the `uiMode = Configuration.UI_MODE_NIGHT_YES` is being used, so that seems to be the case, yes.

The `painter` used for vector images calls:

```kotlin
@Composable
private fun loadVectorResource(
    theme: Resources.Theme,
    res: Resources,
    id: Int,
    changingConfigurations: Int
): ImageVector {
    val imageVectorCache = LocalImageVectorCache.current
    val key = ImageVectorCache.Key(theme, id)
    var imageVectorEntry = imageVectorCache[key]
```

Something tells me the `theme` is the same for both icons.

**Comment by julioromano** [comment]
@jmartinesp @bmarty 
All comments have been addressed.
A further fix has been applied to `ScreenshotTest.kt` as suggested by @jmartinesp to have paparazzi load `-night` resources.

**Comment by julioromano** [comment]
@jmartinesp @bmarty 
Screenshots looks good to me now.
Can you please do a visual double check?

**Review by jmartinesp — APPROVED** [review]
Yes, LGTM now. There are no issues with the screenshots AFAICT.

**Comment by julioromano** [comment]
@bmarty I'm gonna merge this to avoid any conflicts that may arise. You're welcome to write any comments even after merge!

**Comment by bmarty** [comment]
Yes, sorry, I had a look but did not comment. I think it's all fine! Thanks.

**Pull request merged**
