### PR TITLE
Implement a bloom hash store, for faster bloom rendering.

### PR DESCRIPTION
**Pull request by bmarty**
Implement a bloom hash store to render the bloom effect a few hundred milliseconds faster.

 
## Type of change

- [ ] Feature
- [ ] Bugfix
- [x] Technical
- [ ] Other :

## Content

Implement a bloom hash store to render the bloom effect a few hundred milliseconds faster.

## Motivation and context

Visual polish

Logs (extract):
```
12:01:44.755  8635-8635 Bloom render null
12:01:44.786  8635-8635 Bloom render eyKUQG_2D%j[xu~q%MM{ofofIURjs:ofR*M{RjfQazayxut7WBayj[
12:01:45.353  8635-8635 Bloom render eyKUQG_2D%j[xu~q%MM{ofofIURjs:ofR*M{RjfQazayxut7WBayj[
```
First line is first value
Second line of getting the value from store
Third line is when the blur hash is been computed.

Before the PR, it takes 567 ms to display the bloom, with this PR, it takes only 31ms.

Limitation: If the avatar is updated, the previous bloom will be displayed for a few hundred ms, the time to compute the new hash.

## Tests

- Step 1
- Step 2
- Step ...

## Tested devices

- [ ] Physical
- [ ] Emulator
- OS version(s):

## Checklist

- [ ] Changes have been tested on an Android device or Android emulator with API 23
- [ ] UI change has been tested on both light and dark themes
- [ ] Accessibility has been taken into account. See https://github.com/vector-im/element-x-android/blob/develop/CONTRIBUTING.md#accessibility
- [ ] Pull request is based on the develop branch
- [ ] Pull request includes a new file under ./changelog.d. See https://github.com/vector-im/element-x-android/blob/develop/CONTRIBUTING.md#changelog
- [ ] Pull request includes screenshots or videos if containing UI changes
- [ ] Pull request includes a [sign off](https://matrix-org.github.io/synapse/latest/development/contributing_guide.html#sign-off)
- [ ] You've made a self review of your PR

### CODE REVIEW

**Comment by julioromano** [comment]
Just a general comment that doesn't pertain to the code in this PR.

If our usage of blurhash encode/decode currently takes half a sec then I think we're using the blurhash lib in the wrong way.
So perhaps the approach should not be to cache the hash but rather to change how our usage of the blurhash lib work.

This page lists a few "tricks" that can be used to speed up blurhash encoding/decoding: https://github.com/woltapp/blurhash#how-fast-is-encoding-decoding

**Comment by julioromano** [comment]
I've tried to speed up encoding of the blur as mentioned in today's meeting: https://github.com/vector-im/element-x-android/commit/95c46904e4b372ab8777c1cb4aa178b668016a87

With just this tweak the time to encode the blurhash goes from 218ms to 28.4ms (on my machine).

The end result is indistinguishible (see attached images).
faster
original
dark_faster
dark_original

**Comment by bmarty** [comment]
> I've tried to speed up encoding of the blur as mentioned in today's meeting: [95c4690](https://github.com/vector-im/element-x-android/commit/95c46904e4b372ab8777c1cb4aa178b668016a87)
> 
> With just this tweak the time to encode the blurhash goes from 218ms to 28.4ms (on my machine).

@jmartinesp WDYT?

**Comment by jmartinesp** [comment]
> > I've tried to speed up encoding of the blur as mentioned in today's meeting: [95c4690](https://github.com/vector-im/element-x-android/commit/95c46904e4b372ab8777c1cb4aa178b668016a87)
> > With just this tweak the time to encode the blurhash goes from 218ms to 28.4ms (on my machine).
> 
> @jmartinesp WDYT?

I think we should test it with some other avatars with more details and colors in them. I already downscaled it to 64dp, so if we can downscale it to 32px with no side effects, it LGTM.

Also, as a side note on possible improvements: we discarded using Renderscript because it wasn't really efficient for real time blur, but if we only want to apply it once to a bitmap, something like [this](https://github.com/GIGAMOLE/ComposeShadowsPlus/blob/d20cf017d8a95d2d1d7272f6a5941c05f4181e3a/ComposeShadowsPlus/src/main/kotlin/com/gigamole/composeshadowsplus/rsblur/RSBlurShadow.kt) could be benchmarked against the blurhash approach, as it might actually be better performance wise.

**Comment by bmarty** [comment]
OK, let's close this PR then, but we definitely need to iterate on this, to avoid the bloom blink effect.

**Pull request closed without merging**
