### PR TITLE
Feature/bma/fix maestro

### LINKED ISSUE #1066: element.io now supports slidinc sync, so maestro test is failing.
We should use another server to test this user story.

https://github.com/vector-im/element-x-android/blob/develop/.maestro/tests/account/changeServer.yaml#L12

### PR DESCRIPTION
**Pull request by bmarty**
Fix #1066 

Locally, maestro test is failing when leaving a room. Let's see how it's behave on maestro cloud. Action triggered manually: https://github.com/vector-im/element-x-android/actions/runs/5892168780

This PR also contains some minor improvement in the maestro tests.

### CODE REVIEW

**Comment by jmartinesp** [comment]
It seems like [it failed](https://github.com/vector-im/element-x-android/actions/runs/5892168780/job/15980828010) ☹️ .

**Comment by bmarty** [comment]
Yes, this is the issue about the leave room breaking the sync. I think it does not prevent this PR from being merged, at least the test flow is going further...

**Review by jmartinesp — COMMENTED** [review]
In that case, LGTM. Let's hope there is a fix in the Rust SDK for the leave room issue soon 🤞

**Review by jmartinesp — APPROVED** [review]
I guess I pressed the wrong button before because it only added a comment. LGTM (again).

**Pull request merged**
