### PR TITLE
Add content description to voice message attachment sheet

### PR DESCRIPTION
**Pull request by julioromano**
This will add "Voice message" as content description of the voice message icon in the attachment bottom sheet (after long pressing on a voice message).

### CODE REVIEW

**Review by jmartinesp — APPROVED** [review]
The code LGTM and @bmarty already tested it, so approved!

**Review by bmarty — CHANGES_REQUESTED** [review]
Let me check again before merging

**Comment by bmarty** [comment]
The code for message detail bottom sheet is here: https://github.com/vector-im/element-x-android/blob/develop/features/messages/impl/src/main/kotlin/io/element/android/features/messages/impl/actionlist/ActionListView.kt#L316

You are modifying the code which handle a replied to item in the timeline.

Also in this case, the rendering is this one:

image

So I do not think it is necessary to add again the string "Voice message" to the icon. A contentDecription `null` should be fine in this case.

**Comment by julioromano** [comment]
> The code for message detail bottom sheet is here: https://github.com/vector-im/element-x-android/blob/develop/features/messages/impl/src/main/kotlin/io/element/android/features/messages/impl/actionlist/ActionListView.kt#L316
> 
> You are modifying the code which handle a replied to item in the timeline.
> 
> Also in this case, the rendering is this one:
> 
> image
> So I do not think it is necessary to add again the string "Voice message" to the icon. A contentDecription `null` should be fine in this case.

You are right. Will close this.

**Pull request closed without merging**
