### PR TITLE
Remove voice messages feature flag

### PR DESCRIPTION
**Pull request by jonnyandrew**
## Type of change

- [ ] Feature
- [ ] Bugfix
- [x] Technical
- [ ] Other :

## Content

Remove voice messages feature flag.

## Motivation and context

The feature is already enabled by default so this is just cleaning up.

## Tested devices

- [ ] Physical
- [ ] Emulator
- OS version(s):

## Checklist

- [ ] Changes have been tested on an Android device or Android emulator with API 23
- [ ] UI change has been tested on both light and dark themes
- [ ] Accessibility has been taken into account. See https://github.com/vector-im/element-x-android/blob/develop/CONTRIBUTING.md#accessibility
- [x] Pull request is based on the develop branch
- [ ] Pull request includes a new file under ./changelog.d. See https://github.com/vector-im/element-x-android/blob/develop/CONTRIBUTING.md#changelog
- [ ] Pull request includes screenshots or videos if containing UI changes
- [ ] Pull request includes a [sign off](https://matrix-org.github.io/synapse/latest/development/contributing_guide.html#sign-off)
- [ ] You've made a self review of your PR

### CODE REVIEW

**Comment by bmarty** [comment]
Do we really want to remove the feature flag? Is the request to remove it coming from product?
I am asking, because it can be handy for forks to disable the feature if they do not want to have it.

**Comment by jonnyandrew** [comment]
> Do we really want to remove the feature flag? Is the request to remove it coming from product? I am asking, because it can be handy for forks to disable the feature if they do not want to have it.

No it didn't come from product, this was more of an engineering clean-up job.

Shouldn't we remove the feature flags that we're not actively supporting? Otherwise we'll end up with more complexity and lots of code paths that are not always used/tested regularly.

**Comment by bmarty** [comment]
OK thanks. Discussion is in progress internally

**Comment by manuroe** [comment]
We decided that we keep flags in the code for the moment but we want to remove them from any UI including from the "developer options" screen.
@kittykat is going to update the epic template to add this step in the process.

**Comment by jonnyandrew** [comment]
Ok, thanks for the update - I'll close this PR. @bmarty I assume there is nothing further for me to do as we can just hide any feature flag from the UI which is set to on by default (which this flag already is)?

**Comment by bmarty** [comment]
> We decided that we keep flags in the code for the moment but we want to remove them from any UI including from the "developer options" screen. @kittykat is going to update the epic template to add this step in the process.

I do not really understand, why we want to hide this flag from the developer options? The developer options screen is not available in the release version of the app, and we may want the developers to be able to disable any `FeatureFlag` to test the behavior of the app.
The current developer options exposes [all the available FeatureFlags](https://github.com/vector-im/element-x-android/blob/main/features/preferences/impl/src/main/kotlin/io/element/android/features/preferences/impl/developer/DeveloperSettingsPresenter.kt#L78), it's strange to filter some of them out.

**Pull request closed without merging**
