### PR TITLE
 Migrate object to data object in sealed interface / class #1135 

### LINKED ISSUE #1135: Migrate `object` to `data object` in sealed interface / class
Small task, but will get ride of this IDE warning:

image

It will mainly improve the rendering of such object in logs. More details in https://kotlinlang.org/docs/object-declarations.html#data-objects

It may have a very small impact on compiler performance, let's check the compile time by the CI.

### PR DESCRIPTION
**Pull request by bmarty**
Closes #1135

### CODE REVIEW

**Comment by jmartinesp** [comment]
There doesn't seem to be any impact in build times 🟢 !

**Comment by bmarty** [comment]
The generated bytecode is a bit larger, for instance with `RoomMemberDetailsEvents.ClearConfirmationDialog`, once decompiled, we get:

with `object`:

```java
   @Metadata(
      mv = {1, 9, 0},
      k = 1,
      xi = 2,
      d1 = {"\u0000\f\n\u0002\u0018\u0002\n\u0002\u0018\u0002\n\u0002\b\u0002\bÆ\u0002\u0018\u00002\u00020\u0001B\u0007\b\u0002¢\u0006\u0002\u0010\u0002¨\u0006\u0003"},
      d2 = {"Lio/element/android/features/roomdetails/impl/members/details/RoomMemberDetailsEvents$ClearConfirmationDialog;", "Lio/element/android/features/roomdetails/impl/members/details/RoomMemberDetailsEvents;", "()V", "impl_debug"}
   )
   public static final class ClearConfirmationDialog implements RoomMemberDetailsEvents {
      @NotNull
      public static final ClearConfirmationDialog INSTANCE;

      private ClearConfirmationDialog() {
      }

      static {
         ClearConfirmationDialog var0 = new ClearConfirmationDialog();
         INSTANCE = var0;
      }
   }
```

with `data object`:

```java
   @Metadata(
      mv = {1, 9, 0},
      k = 1,
      xi = 2,
      d1 = {"\u0000$\n\u0002\u0018\u0002\n\u0002\u0018\u0002\n\u0002\b\u0002\n\u0002\u0010\u000b\n\u0000\n\u0002\u0010\u0000\n\u0000\n\u0002\u0010\b\n\u0000\n\u0002\u0010\u000e\n\u0000\bÆ\n\u0018\u00002\u00020\u0001B\u0007\b\u0002¢\u0006\u0002\u0010\u0002J\u0013\u0010\u0003\u001a\u00020\u00042\b\u0010\u0005\u001a\u0004\u0018\u00010\u0006HÖ\u0003J\t\u0010\u0007\u001a\u00020\bHÖ\u0001J\t\u0010\t\u001a\u00020\nHÖ\u0001¨\u0006\u000b"},
      d2 = {"Lio/element/android/features/roomdetails/impl/members/details/RoomMemberDetailsEvents$ClearConfirmationDialog;", "Lio/element/android/features/roomdetails/impl/members/details/RoomMemberDetailsEvents;", "()V", "equals", "", "other", "", "hashCode", "", "toString", "", "impl_debug"}
   )
   public static final class ClearConfirmationDialog implements RoomMemberDetailsEvents {
      @NotNull
      public static final ClearConfirmationDialog INSTANCE;

      private ClearConfirmationDialog() {
      }

      static {
         ClearConfirmationDialog var0 = new ClearConfirmationDialog();
         INSTANCE = var0;
      }

      @NotNull
      public String toString() {
         return "ClearConfirmationDialog";
      }

      public int hashCode() {
         return 1651779154;
      }

      public boolean equals(@Nullable Object var1) {
         if (this != var1) {
            if (!(var1 instanceof ClearConfirmationDialog)) {
               return false;
            }

            ClearConfirmationDialog var2 = (ClearConfirmationDialog)var1;
         }

         return true;
      }
   }
```

This has a (small) impact on the APK size, so finally, I am not sure that this is what we want...

**Comment by jmartinesp** [comment]
> The generated bytecode is a bit larger

I wouldn't worry about that.

> This has a (small) impact on the APK size

How large? Also, once we build for release mode it should strip those `toString()` methods that aren't used, so maybe we won't notice any changes?

**Comment by jmartinesp** [comment]
> Also I think Proguard will never strip out equals, hashCode and toString methods.

You're right, they're never removed ☹️ .

> Not a big deal, but for a minor advantage.

That seems reasonable to me, but if we think it's too much we can revert this. I think having more readable logs is worth it.

**Review by bmarty — COMMENTED** [review]
OK, after discussing with the team, let's merge this PR.

**Pull request merged**
