### PR TITLE
Fix using local rust aar

### PR DESCRIPTION
**Pull request by csmith**
The rustsdk library wasn't included in the gradle build because it still used a groovy build file (and settings.gradle includes projects based on `build.gradle.kts` existing).

Also reword the onboarding docs slightly to clarify the deps that need changing

### CODE REVIEW

**Comment by jmartinesp** [comment]
@csmith can you rebase/merge develop into the PR? It should at least fix the issues with Danger.

**Review by ganfra — COMMENTED** [review]
Thanks for the changes.
`rustsdk` library is included manually in the settings file, so you should also take care of removing the line.
`include(":libraries:rustsdk")`

**Comment by csmith** [comment]
> Thanks for the changes. `rustsdk` library is included manually in the settings file, so you should also take care of removing the line. `include(":libraries:rustsdk")`

Oh, odd. I wonder why it wasn't being included before then :thinking:

**Comment by jmartinesp** [comment]
@csmith #292 was just merged to develop, can you merge the branch so the CI passes?

**Comment by csmith** [comment]
This is now just a few document tweaks, as converting to kts was done in 5a3b30a0e42705cf6ced66734fe39fefb1670fc6

**Review by ganfra — APPROVED** [review]

**Pull request merged**
