### PR TITLE
org.gradle.jvmargs=-Xmx4g

### PR DESCRIPTION
**Pull request by julioromano**
I have to do it locally every time i checkout a branch. Perhaps it's best if we push this to origin.

### CODE REVIEW

**Comment by jmartinesp** [comment]
I think it's a good idea to bump the default value since it's too low for some tasks now (lint, tests sometimes), but you could just add this line to your `~/.gradle/gradle.properties` and it will override the default one in the project too if I'm not mistaken.

**Comment by julioromano** [comment]
> I think it's a good idea to bump the default value since it's too low for some tasks now (lint, tests sometimes), but you could just add this line to your `~/.gradle/gradle.properties` and it will override the default one in the project too if I'm not mistaken.

Is there any downside in bumping the one in origin too? The tests ran pretty fast in this PR.

**Comment by jmartinesp** [comment]
> Is there any downside in bumping the one in origin too? The tests ran pretty fast in this PR.

No, I'm ok with increasing the max heap size. Let's see it @ganfra agrees too.

**Review by ganfra — APPROVED** [review]
Ok for me!

**Pull request merged**
