### PR TITLE
Fix scaling of composer UI

### PR DESCRIPTION
**Pull request by jonnyandrew**
## Type of change

- [ ] Feature
- [x] Bugfix
- [ ] Technical
- [ ] Other :

## Content

Stop scaling icons and other non-text UI with the system font scale.

## Motivation and context

The system provides two mechanisms to scale UI: the font size setting and the display size setting. This change ensures that UI components are not affected by both settings and that text can be scaled independently.

## Tests

- Step 1
- Step 2
- Step ...

## Tested devices

- [ ] Physical
- [x] Emulator
- OS version(s):

## Checklist

- [ ] Changes have been tested on an Android device or Android emulator with API 23
- [ ] UI change has been tested on both light and dark themes
- [ ] Accessibility has been taken into account. See https://github.com/vector-im/element-x-android/blob/develop/CONTRIBUTING.md#accessibility
- [x] Pull request is based on the develop branch
- [ ] Pull request includes a new file under ./changelog.d. See https://github.com/vector-im/element-x-android/blob/develop/CONTRIBUTING.md#changelog
- [ ] Pull request includes screenshots or videos if containing UI changes
- [ ] Pull request includes a [sign off](https://matrix-org.github.io/synapse/latest/development/contributing_guide.html#sign-off)
- [ ] You've made a self review of your PR

### CODE REVIEW

**Comment by bmarty** [comment]
The idea of using `applyScaleUp` was to keep coherency of UI when changing the system setting for font scale. Is is still OK after these changes?

**Comment by jonnyandrew** [comment]
> The idea of using `applyScaleUp` was to keep coherency of UI when changing the system setting for font scale. Is is still OK after these changes?

The coherency is affected because the text in the editor can now be increased independently from the surrounding UI icons, buttons etc. But, having looked at other apps including system apps and a few other chat apps it seems this is the way it's supposed to work; the font size setting seems only to affect text whereas the display size can be used to scale non-text UI including icons.

**Comment by bmarty** [comment]
> So although the UI isn't as nice looking, users with a large font scale setting would have this same experience across the whole system.

So users will have the same **bad** experience IMO.

**Comment by jonnyandrew** [comment]
It is bad aesthetically but UX wise but the alternative might be worse: consider a user might have increased their display size so that they are able to touch buttons easily and also increased their font size. In this scenario, our composer buttons are scaled twice and only a little width is remaining for the text input. As a result the input text will be wrapped quite aggressively. I'm not sure if this PR is the right solution but it does improve accessibility in this regard.

**Review by julioromano — APPROVED** [review]

**Comment by jonnyandrew** [comment]
@bmarty are you happy for me to merge based on [this rationale](https://github.com/vector-im/element-x-android/pull/1691#issuecomment-1785455628)?

**Comment by bmarty** [comment]
> @bmarty are you happy for me to merge based on [this rationale](https://github.com/vector-im/element-x-android/pull/1691#issuecomment-1785455628)?

Yes, OK, thanks for clarifying!

**Pull request merged**
