### PR TITLE
Check code

### PR DESCRIPTION
**Pull request by bmarty**
Import tool from Element Android which help to detect forbidden pattern in our codebase.

### CODE REVIEW

**Comment by julioromano** [comment]
I see some code changes that appear unrelated to the addition of the check_code_quality.sh script. Can you offer some more context?

**Review by julioromano — COMMENTED** [review]
I see some code changes that appear unrelated to the addition of the check_code_quality.sh script. What are those for?

**Comment by bmarty** [comment]
> I see some code changes that appear unrelated to the addition of the check_code_quality.sh script. What are those for?

- We should not use `System.currentTimeMillis()` directly, it's better to inject a Clock.
- Using `"$o.s"` is forbidden because it can lead to unexpected log.
- For the rest, this is formatting.

**Comment by julioromano** [comment]
> > I see some code changes that appear unrelated to the addition of the check_code_quality.sh script. What are those for?
> 
> * We should not use `System.currentTimeMillis()` directly, it's better to inject a Clock.
> * Using `"$o.s"` is forbidden because it can lead to unexpected log.
> * For the rest, this is formatting.

I see, but is it the `check_code_quality.sh` that fixed those errors or was it you manually?

**Review by julioromano — APPROVED** [review]
I'll LGTM this in the meantime to not become a blocker. Though please try to answer my comment above.

**Comment by bmarty** [comment]
I fixed the issue manually.

**Pull request merged**
