### PR TITLE
Sync Strings

### PR DESCRIPTION
**Pull request by ElementBot**
- Update Strings from Localazy

### CODE REVIEW

**Review by julioromano — APPROVED** [review]
LGTM though let's see if @bmarty agrees as he's more up to date with what's going on with localizations.

**Review by bmarty — APPROVED** [review]
OK for the French part.

**Comment by bmarty** [comment]
Recording sc: https://github.com/vector-im/element-x-android/actions/runs/6454440104

**Review by bmarty — APPROVED** [review]
OK

**Pull request merged**
